name: Create Linear ticket

on:
  pull_request:
    types: [opened]

jobs:
  linear-ticket:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Create Linear ticket
        id: createIssue
        uses: ctriolo/action-create-linear-issue@v0.5
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          linear-team-key: "ECO"
          linear-issue-title: ${{ github.event.pull_request.title }}
          linear-issue-description: ${{ github.event.pull_request.body }}
          linear-attachment-url: ${{ github.event.pull_request.html_url }}
          linear-attachment-title: ${{ github.event.pull_request.title }}

      - name: Create comment for Linear ticket link
        uses: marocchino/sticky-pull-request-comment@v2.8.0
        with:
          GITHUB_TOKEN: ${{ secrets.CLERK_COOKIE_PAT }}
          number: ${{ github.event.issue.number }}
          header: linear-issue-url
          message: |
            A Linear ticket has been created for this PR: ${{ steps.createIssue.outputs.linear-issue-url }}