name: Slack Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  slack-notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false
      - name: Convert PR body to Slack format
        id: slackify
        uses: LoveToKnow/slackify-markdown-action@v1.1.1
        with:
          text: ${{ env.PULL_REQUEST_BODY }}
      - name: Generate notification payload
        id: notification
        env:
          TITLE: ${{ github.event.pull_request.title }}
          USER_LOGIN: ${{ github.event.pull_request.user.login }}
          HTML_URL: ${{ github.event.pull_request.html_url }}
        run: |
          payload=$(node ./.github/utils/slack-notify.mjs '${{ env.TITLE }}' '${{ env.USER_LOGIN }}' '${{ env.HTML_URL }}' '${{ steps.slackify.outputs.text }}')
          echo "payload=${payload//$'\n'/'%0A'}" >> $GITHUB_OUTPUT
      - name: Send PR to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: ${{ steps.notification.outputs.payload }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CHANGELOG_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK